# spring=======================================================
server:
  port: 5354

# redis=======================================================
spring:

  # datasource=======================================================
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://8.134.180.139:3306/piggy_shop?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: dev
    password: asdfghjkl
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      max-active: 10 # 最大活跃数量 默认8
      min-idle: 2 # 最小空闲数 默认0
      initial-size: 5 # 初始连接数
      max-wait: 2000 # 获取连接最大等待时间 默认 -1
      validation-query: select 1
      validation-query-timeout: 5000
      time-between-eviction-runs-millis: 2000 # 间隔多久进行检测需要关闭的空闲连接
      min-evictable-idle-time-millis: 600000 # 配置连接在池中最小生存的时间
      max-wait-thread-count: 20 # 最大等待线程数

  mail:
    host: smtp.163.com
    port: 465
    username: 13415143041@163.com
    password: WJNAUPBFZYBZPTKO
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          ssl:
            trust: smtp.163.com
          auth: true
          starttls:
            enable: true
            required: true
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
            port: 465


# mybatis=======================================================
mybatis:
  configuration:
    map-underscore-to-camel-case: true
